name       : raptor2
version    : 2.0.15
release    : 2
source     :
    - http://download.librdf.org/source/raptor2-2.0.15.tar.gz : ada7f0ba54787b33485d090d3d2680533520cd4426d2f7fb4782dd4a6a1480ed
license    : GPL-2.0
component  : programming.library
summary    : Library that provides a set of parsers and serializers that generate Resource Description Framework (RDF) triples.
description: |
    Library that provides a set of parsers and serializers that generate Resource Description Framework (RDF) triples by parsing syntaxes or serialize the triples into a syntax.
builddeps  :
    - pkgconfig(icu-i18n)
    - pkgconfig(libcurl)
    - pkgconfig(libxslt)
setup      : |
    %patch -p1 < $pkgfiles/0001-Calcualte-max-nspace-declarations-correctly-for-XML-.patch
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    make check
